import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
import pandas as pd


def build_digest_html(all_results: dict) -> str:
    """Build an HTML email body summarising the day's matched jobs."""
    today = datetime.now().strftime("%A %d %B %Y")

    total = sum(len(df) for df in all_results.values())

    if total == 0:
        return f"""
        <html><body style="font-family: Arial, sans-serif; padding: 20px;">
        <h2>Job Pipeline Digest - {today}</h2>
        <p>No new matched jobs found today. The pipeline ran successfully but nothing passed the quality filters.</p>
        <p>This usually means Apify credits are exhausted or the free sources had no relevant listings. Check your Apify billing if this persists.</p>
        </body></html>
        """

    rows_html = ""
    for campaign_name, df in all_results.items():
        if df.empty:
            continue

        rows_html += f"""
        <tr style="background-color: #1F3864; color: white;">
            <td colspan="5" style="padding: 10px; font-weight: bold;">
                {campaign_name} ({len(df)} matches)
            </td>
        </tr>
        """

        for _, row in df.iterrows():
            score      = row.get("match_score", 0)
            score_color = "#27ae60" if score >= 0.55 else "#f39c12" if score >= 0.45 else "#e74c3c"

            rows_html += f"""
            <tr style="border-bottom: 1px solid #eee;">
                <td style="padding: 8px;">{row.get('title', '')}</td>
                <td style="padding: 8px;">{row.get('company', '')}</td>
                <td style="padding: 8px;">{row.get('source', '')}</td>
                <td style="padding: 8px; text-align: center;">
                    <span style="color: {score_color}; font-weight: bold;">{score:.3f}</span>
                </td>
                <td style="padding: 8px;">
                    <a href="{row.get('url', '#')}" style="color: #2980b9;">Apply</a>
                </td>
            </tr>
            """

    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; padding: 20px; background-color: #f9f9f9;">
        <div style="max-width: 700px; margin: 0 auto; background: white; padding: 24px; border-radius: 8px;">
            <h2 style="color: #1F3864; margin-bottom: 4px;">Job Pipeline Digest</h2>
            <p style="color: #666; margin-top: 0;">{today} | {total} new matches</p>

            <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
                <tr style="background-color: #f0f0f0;">
                    <th style="padding: 8px; text-align: left;">Title</th>
                    <th style="padding: 8px; text-align: left;">Company</th>
                    <th style="padding: 8px; text-align: left;">Source</th>
                    <th style="padding: 8px; text-align: center;">Score</th>
                    <th style="padding: 8px; text-align: left;">Link</th>
                </tr>
                {rows_html}
            </table>

            <p style="color: #999; font-size: 12px; margin-top: 20px;">
                Generated by your job pipeline. Open the Excel tracker for full details.
            </p>
        </div>
    </body>
    </html>
    """
    return html


def send_email_digest(all_results: dict, recipient: str):
    """
    Send the daily digest email via Gmail SMTP.
    Requires an App Password — NOT your regular Gmail password.

    To set up:
    1. Go to myaccount.google.com → Security → 2-Step Verification (enable it)
    2. Then go to myaccount.google.com/apppasswords
    3. Create an App Password for "Mail"
    4. Add to your .env: GMAIL_APP_PASSWORD=your_16_char_password
    """
    from dotenv import load_dotenv
    load_dotenv()

    sender   = os.getenv("GMAIL_ADDRESS", recipient)
    password = os.getenv("GMAIL_APP_PASSWORD", "")

    if not password:
        print("  ERROR: GMAIL_APP_PASSWORD not found in .env")
        print("  To set up:")
        print("    1. Enable 2-Step Verification on your Google account")
        print("    2. Go to myaccount.google.com/apppasswords")
        print("    3. Create an App Password for 'Mail'")
        print("    4. Add to .env: GMAIL_APP_PASSWORD=your_16_char_password")
        print("    5. Add to .env: GMAIL_ADDRESS=your_email@gmail.com")
        return False

    today = datetime.now().strftime("%Y-%m-%d")
    total = sum(len(df) for df in all_results.values())

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Job Pipeline: {total} new matches - {today}"
    msg["From"]    = sender
    msg["To"]      = recipient

    html_body = build_digest_html(all_results)
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
            server.login(sender, password)
            server.sendmail(sender, recipient, msg.as_string())
        print(f"  Digest sent to {recipient}")
        return True
    except Exception as e:
        print(f"  Email send failed: {e}")
        return False


def run_alerter(tailored_results: dict) -> bool:
    """
    Send daily digest email with matched jobs.
    Input: dict of {campaign_name: df}
    """
    print("\n=== MODULE 6: Daily digest alert ===")

    total = sum(len(df) for df in tailored_results.values())
    print(f"  Jobs to include in digest: {total}")

    recipient = "oluwabolaji60@gmail.com"
    success   = send_email_digest(tailored_results, recipient)

    if success:
        print(f"\n=== Module 6 complete — digest sent ===")
    else:
        print(f"\n=== Module 6 complete — digest NOT sent (check .env) ===")

    return success


if __name__ == "__main__":
    # Quick test with dummy data
    import pandas as pd

    test_data = {
        "analyst_nigeria_africa": pd.DataFrame([{
            "title":       "Test Data Analyst",
            "company":     "Test Company",
            "source":      "LinkedIn",
            "location":    "Lagos, Nigeria",
            "match_score": 0.65,
            "url":         "https://example.com/job1",
        }])
    }

    print("\n--- Testing email digest with dummy data ---")
    run_alerter(test_data)
    print("\n✓ Module 6 test complete")